version: '3'
services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    image: emmyjay387/node-app
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
